version: '3.5'

services:
    php:
        image: hanabosocom/php-dev:php-8.1-alpine
        user: ${DEV_UID}:${DEV_GID}
        environment:
            - APP_ENV=dev
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - COMPOSER_HOME=${HOME}/dev/.composer
            - MONGODB_HOST=mongo
        volumes:
            - ./:/var/www:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached

    mongo:
        image: mongo:latest
        volumes:
            - mongo:/data/db

volumes:
    mongo: {}
