version: '3.3'

services:
    php:
        image: hanabosocom/php-dev:php-7.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            COMPOSER_HOME: ${HOME}/dev/.composer
        volumes:
            - ./:/var/www
            - ${SSH_AUTH_SOCK}:${SSH_AUTH}
            - ${HOME}/.composer:/srv/.composer

    mongo:
        image: mongo:latest
        volumes:
            - mongo:/data/db

volumes:
    mongo: {}
