version: '3.5'

services:
    php:
        image: hanabosocom/php-dev:php-7.4
        user: ${DEV_UID}:${DEV_GID}
        environment:
            - APP_ENV=dev
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - COMPOSER_HOME=${HOME}/dev/.composer
        volumes:
            - ./:/var/www
            - ${SSH_AUTH_SOCK}:${SSH_AUTH}
            - ${HOME}/dev/.composer:${HOME}/dev/.composer

    mongo:
        image: mongo:latest
        volumes:
            - mongo:/data/db

volumes:
    mongo: {}
